# Generated by Django 2.0.4 on 2018-04-30 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HotelName', models.CharField(max_length=50)),
                ('HotelStars', models.IntegerField()),
                ('HotelFood', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PointName', models.CharField(max_length=50)),
                ('PointDuration', models.IntegerField()),
                ('DateArrival', models.DateField()),
                ('DateDeparture', models.DateField()),
                ('PointCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.City')),
                ('PointHotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TourName', models.CharField(max_length=50)),
                ('TourDateStart', models.DateField()),
                ('TourDateEnd', models.DateField()),
                ('TourDuration', models.IntegerField()),
                ('ContactCount', models.IntegerField()),
                ('PriceAdult', models.IntegerField()),
                ('PriceChild', models.IntegerField()),
                ('TourImage', models.ImageField(upload_to='media/catalog')),
                ('Comments', models.TextField()),
                ('TourCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
                ('TourCountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Country')),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='PointTour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Tour'),
        ),
    ]
