# Generated by Django 2.0.4 on 2018-05-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180430_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.CharField(default='my', max_length=200),
        ),
    ]
